# -*- coding: utf-8 -*-
"""contexual-bandit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqfZNcie-JB6Dz95u_Myzy7V2rhx5eFy
"""

!pip install mabwiser pandas numpy matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from mabwiser.mab import MAB
from mabwiser.mab import LearningPolicy

np.random.seed(42)
n_blocks = 50  # number of time blocks

df = pd.DataFrame({
    'block_focus': np.random.rand(n_blocks),
    'keystroke_intervals_mean': np.random.normal(200, 50, n_blocks),
    'burstiness': np.random.rand(n_blocks),
    'scroll_rate': np.random.randint(0, 100, n_blocks),
    'idle_time_percent': np.random.rand(n_blocks) * 100,
    'microEMA': np.random.rand(n_blocks),
    'sleep_hours_prev_night': np.random.randint(4, 10, n_blocks),
    'action': np.random.choice(['morning', 'afternoon', 'evening'], n_blocks)
})

# Reward = weighted combination of focus + microEMA (dummy)
df['reward'] = 0.7 * df['block_focus'] + 0.3 * df['microEMA']

print("=== Dummy Dataset Preview ===")
print(df.head())

context_features = [
    'block_focus', 'keystroke_intervals_mean', 'burstiness',
    'scroll_rate', 'idle_time_percent', 'microEMA', 'sleep_hours_prev_night'
]

contexts = df[context_features].values
actions = df['action'].values
rewards = df['reward'].values

arm_mapping = {'morning': 0, 'afternoon': 1, 'evening': 2}
actions_encoded = np.array([arm_mapping[a] for a in actions], dtype=int)
actions_series = pd.Series(actions_encoded) # Convert to Pandas Series
rewards_array = np.array(rewards, dtype=float)
context_df = pd.DataFrame(contexts, columns=context_features).astype(float)

mab = MAB(
    arms=[0, 1, 2],
    learning_policy=LearningPolicy.LinUCB(alpha=1.25)
)

mab.partial_fit(actions_encoded, rewards_array, context_df)
print("=== Bandit trained successfully ===")

new_context = pd.DataFrame([[0.9, 180, 0.2, 40, 5, 0.85, 8]], columns=context_features).astype(float)
best_action_encoded = mab.predict(new_context)
best_action = [k for k, v in arm_mapping.items() if v == best_action_encoded][0]
print("Recommended study slot for this context:", best_action)

simulated_contexts = pd.DataFrame({
    'block_focus': np.random.rand(24),
    'keystroke_intervals_mean': np.random.normal(200, 50, 24),
    'burstiness': np.random.rand(24),
    'scroll_rate': np.random.randint(0, 100, 24),
    'idle_time_percent': np.random.rand(24) * 100,
    'microEMA': np.random.rand(24),
    'sleep_hours_prev_night': np.random.randint(4, 10, 24)
})

predictions_encoded = mab.predict(simulated_contexts)
predictions = [k for idx in predictions_encoded for k, v in arm_mapping.items() if v == idx]

# Simple heatmap plot
plt.figure(figsize=(12, 4))
sns.heatmap(np.array(predictions_encoded).reshape(1, -1), annot=np.array(predictions).reshape(1, -1),
            fmt='', cmap='coolwarm', cbar=False)
plt.title("Predicted Best Study Slots Across 24 Simulated Hours")
plt.xlabel("Hour")
plt.yticks([])
plt.show()